services:
  - docker

install:
  - docker build -t app example

script:
  - |
    docker run --rm -it \
      -v "$(pwd)/example":/src \
      -v /var/run/docker.sock:/var/run/docker.sock \
    iorubs/dgoss run app
